export const MODULE_NAME = 'LOGIN_MODULE'

export const actionTypes = {
  ENTER_SCHOOL_CODE: `${MODULE_NAME}/ENTER_SCHOOL_CODE`,
  ENTER_SCHOOL_CODE_SUCCESS: `${MODULE_NAME}/ENTER_SCHOOL_CODE_SUCCESS`,
  ENTER_SCHOOL_CODE_FAILURE: `${MODULE_NAME}/ENTER_SCHOOL_CODE_FAILURE`,
}
